using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using TasinmazStaj.Interfaces;

namespace TasinmazStaj.Services
{
    public class GeometryService : IGeometryService
    {
        private readonly RemsDbContext _dbContext;

        public GeometryService(RemsDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public Task<GeometryResult> ComputeIntersectionAsync(string label1, string label2)
        {
            throw new NotImplementedException();
        }

        public Task<List<GeometryResult>> GetAutoSelectGeometriesAsync()
        {
            throw new NotImplementedException();
        }

        // ... (Keep existing GetAutoSelectGeometriesAsync and ComputeIntersectionAsync methods) ...

        public async Task<GeometryResult> SaveUnionResultAsync(SaveGeometryDto dto)
        {
            // Map the frontend DTO directly to your Entity
            var newRegion = new GeometryResult
            {
                Label = dto.ResultType,         // "D" or "E"
                Wkt = dto.ResultWkt,            // The union polygon generated by the frontend
                SurfaceArea = dto.CalculatedArea, // The area calculated by the frontend
                CreatedAt = DateTime.UtcNow
            };

            _dbContext.GeometryResults.Add(newRegion);
            await _dbContext.SaveChangesAsync();

            return newRegion;
        }

        public Task<GeometryResult> SaveUnionResultAsync(SaveGeometryDto dto, int v)
        {
            throw new NotImplementedException();
        }
    }
}